name: ci.uffs.cc
on:
  push:
    branches:    
      - master
      - dev
env:
  BUILD_HOST: ci.uffs.cc
  BUILD_WEB_DIRECTORY: /home/ccuffsci/ci.uffs.cc/aura-nlp
  BUILD_WEB_URL: https://ci.uffs.cc/aura-nlp
jobs:
  build-deploy-audit:
    name: Build, deploy and audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Prepare deploy server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.BUILD_HOST }}
        username: ${{ secrets.CI_USERNAME }}
        password: ${{ secrets.CI_PASSWORD }}
        script: |
          mkdir -p ${{ env.BUILD_WEB_DIRECTORY }}/${{ steps.extract_branch.outputs.branch }}/${{ github.sha }}
          mkdir -p ${{ env.BUILD_WEB_DIRECTORY }}/${{ steps.extract_branch.outputs.branch }}/${{ github.sha }}/_report
    - name: Summary
      run: |
        echo "Summary:"
        echo " Live URL: ${{ env.BUILD_WEB_URL }}/${{ steps.extract_branch.outputs.branch }}/${{ github.sha }}"